#!/bin/bash

check() {
        if [ "$(whoami)" != "root" ]
           then
               echo "You need to login as root to use raws gen-ssl! Sorry!" | lolcat -a -s 100;
               exit 1
        fi
        if [ -d "/etc/letsencrypt/live/$1" ]; then
          echo "Looks like You Already Have Generate A SSL For $1!" | lolcat -a -s 100;
          echo "Sorry We Can't Genereate A SSL For A Domain Which Already Have One!" | lolcat -a -s 100;
          exit 1
        fi
}
vIP() {
if [ -f "/root/.cf.ini" ]; then
else 
    echo "Please put your clouflare api into /root/.cf.ini https://certbot-dns-cloudflare.readthedocs.io/en/stable/"
    exit 1
fi
}

genit() {
        clear
        echo -e "|=======================|" | lolcat -a -s 100;
        echo -e "| ROOT CHECK       : OK |"
        echo -e "| CLOUDFLARE CHECK : OK |"
        echo -e "|=======================|" | lolcat -a -s 100;
        certbot certonly --dns-cloudflare --dns-cloudflare-credentials ~/.cf.ini -d *.$1
        if [ -d "/etc/letsencrypt/live/$1" ]; then
          echo "Your wildcard was generated and stored @ /etc/letsencrypt/live/$1"
        else
          echo "Something went wrong please scroll up and read certbot logs"
        fi
}

if [ "$1" == 'gen-ssl' ] && [ "$2" ]; then
      check $2; vIP $2; genit $2;
fi
